id: P6FF6F644
initial_creation_type: input
source_metadata:
  title: Tārā Series
  language: en
  description: 'A series of texts related to the noble saviouress Tārā (sgrol ma):'
  volume:
    4a8f292da77f46a88308bdd4c63a838f:
      title: Introduction to Tārā
      parent: Introduction
    1fc5247314ac42c394a5f1c6f8b793ab:
      title: A Brief History of the Sacred Image of White Tārā
      parent: History
    4d7e57ebc26b4fc99fc6779d2ee7616b:
      title: 'The Fount of Longevity: The Chimé Pakmé Nyingtik Lineage Prayer'
      parent: Lineage Prayers
    041aa084866044a6bfdb4eba9eed6bc3:
      title: 'The Concentration of Blessings: Red Tārā Lineage Prayer'
      parent: Lineage Prayers
    0ce83fae52854f83b21345a2330c8267:
      title: 'The Garland of Utpala Flowers: A Prayer to the Masters of the Lineage
        of Zabtik Drolchok'
      parent: Lineage Prayers
    ac2c6253074e4e5b9138396975363503:
      title: An Extremely Concise Praise of the Twenty-One Tārās
      parent: Praise
    96ec4e38d435407fa668962c35d21d0a:
      title: The Praise to Tārā with Twenty-One Verses of Homage and The Excellent
        Benefits of Reciting the Praise
      parent: Praise
    0eb32aa43b4649a7a6540ee0a2445317:
      title: 'The Fulfilment of All Aspirations: In Praise of Noble Tārā'
      parent: Praise
    2ade67fb2db94076a9cfe8b0a95cd667:
      title: 'A Surge of Faith: Verses In Praise of Tārā'
      parent: Praise
    2553217ed2d74d8e8c23fc0af66f4c6e:
      title: An Outline of The Praise to Tārā with Twenty-One Verses of Homage
      parent: Praise
    05654a485f9948c2a0dc930a7a9a60ba:
      title: 'Brilliant Rays of Light: A Commentary on the Praise to Tārā'
      parent: Praise
    83e61d9a9d8b4467b39baa4e68331ac8:
      title: A Prayer to Tārā
      parent: Prayers
    286e66cbe1a24043be450d6080ec2d05:
      title: Prayer to Ārya Tārā
      parent: Prayers
    67bb83d7febe4a418b5f4d0ee265a3dd:
      title: A Concise Supplication to the Most Noble Tārā
      parent: Prayers
    7f3fe9e3dd48407da85dca289dd776b6:
      title: 'Prayer to Tārā: A Sevenfold Supplication for Protection'
      parent: Prayers
    23d4a72c211c46c1affd2af49c874bcd:
      title: A Short Supplication to Tārā
      parent: Prayers
    097d7086899349b0aec23eadb8e2860d:
      title: 'Averting Obstructive Circumstances: A Prayer to Tārā'
      parent: Prayers
    92a9790498e34f498c04669766926efd:
      title: 'Eliminator of Suffering: A Prayer to the Venerable and Exalted Tārā'
      parent: Prayers
    c8c0338ba0c04592ae17039b5cd7d1ef:
      title: Prayer to Noble White Tārā
      parent: Prayers
    6c5ca23264ee4f90b8de6529487f04e8:
      title: Prayer to Reverend and Noble Tārā
      parent: Prayers
    b1c49a15f39d42f6a5999d5d48111847:
      title: 'The Sweet-Sounding Song that Fulfils All Aims: A Prayer to Noble Tārā
        Combined with Her Root Mantra'
      parent: Prayers
    3ac40e97f4e74add80a7521f35a96d59:
      title: Prayer to Jetsün Tārā
      parent: Prayers
    3aee637f4ad64fad8c6e7e525a20f453:
      title: Brief Homage to the Twenty-One Tārās
      parent: Prayers
    bd78f30acc034b2a83aeb6dc4607d2cd:
      title: Prayer to Tārā, Combined with Her Mantra
      parent: Prayers
    7c9645b9d8ca40f18ecd4c138fcc2904:
      title: Aspiration Prayer from Tārā Sādhana
      parent: Prayers
    c66b88e2f7204b34bf897a5b352bde17:
      title: A Supplication to Noble Tārā, The Wish-Fulfilling Cornucopia
      parent: Prayers
    ccf6a6dd65a949f282311b83041826a6:
      title: 'Burgeoning Benefit and Happiness: An Aspiration to be Reborn in the
        Land of Turquoise Leaves'
      parent: Prayers
    dee949a1d591446c969fc663c041c69e:
      title: A Means to Pacify the Fear of Natural Disasters
      parent: Sādhanas
    c26b31b82c094c40bbd00b38867b0c7e:
      title: Concise White Tārā Sādhana
      parent: Sādhanas
    17870f1b2ba9424b9ad6d53d398a3214:
      title: 'Swift Enchantment of the Three Realms: A Sādhana of Red Tārā'
      parent: Sādhanas
    3959eb50c2a9467aab41b20422190210:
      title: 'Adornment of Lord Nāgārjuna’s Wisdom Mind: The Fourfold Maṇḍala Offering
        to Tārā'
      parent: Sādhanas
    9522cb49d50b4a1c872f9a3c774de2a9:
      title: 'A Shower of Blessings: A Sādhana of Blue-Green Tārā'
      parent: Sādhanas
    491b9e6bb72e484a892c3b535eb32520:
      title: A Concise Sang Offering to Tārā
      parent: Sang Offering
    084953e2cac34a91a09afda467b56c90:
      title: Seven-Branch Offering to Tārā
      parent: Seven-Branch
    091174231c604e8d9ed31c576c115f47:
      title: 'Essence of Accomplishment: A Concise Feast-Offering to Noble Tārā'
      parent: Tsok
    877c86554976480aa9c15da37e266e0f:
      title: Windhorse Practice of Tārā
      parent: Windhorse
    8d2a5ae7b5ca490ea669fd24e0b535f3:
      title: Brief Windhorse Practice of Tārā
      parent: Windhorse
created_at: '2022-03-01T06:04:43.662417'
last_modified_at: '2022-03-01T06:04:43.662424'
